const WPL_COMPLETION_TABLE = [
  {
    label: 'peek_symbol',
    kind: 'type',
    description: 'Preview match without consuming input',
    example: 'peek_symbol(peek_symbol)',
    insertText: 'peek_symbol(${peek_symbol})',
  },
  {
    label: 'symbol',
    kind: 'type',
    description: 'Exact match for specified string',
    example: 'symbol(symbol)',
    insertText: 'symbol(${symbol})',
  },
  {
    label: 'bool',
    kind: 'type',
    description: 'Boolean value, matches true/false',
    example: 'true',
    insertText: 'bool',
  },
  {
    label: 'chars',
    kind: 'type',
    description: 'String, quoted or bare',
    example: '"hello" / hello',
    insertText: 'chars',
  },
  {
    label: 'digit',
    kind: 'type',
    description: 'Integer',
    example: '123 / -456',
    insertText: 'digit',
  },
  {
    label: 'float',
    kind: 'type',
    description: 'Float',
    example: '3.14 / -0.5',
    insertText: 'float',
  },
  {
    label: 'time_3339',
    kind: 'type',
    description: 'RFC3339/ISO 8601 time',
    example: '2026-01-19T12:34:56Z / 2022-03-21T12:34:56+00:00',
    insertText: 'time_3339',
  },
  {
    label: 'time_2822',
    kind: 'type',
    description: 'RFC2822 email time format',
    example: 'Mon, 07 Jul 2025 09:20:32 +0000',
    insertText: 'time_2822',
  },
  {
    label: 'time/clf',
    kind: 'type',
    description: 'Common Log Format time',
    example: '[06/Aug/2019:12:12:19 +0800]',
    insertText: 'time/clf',
  },
  {
    label: 'time_timestamp',
    kind: 'type',
    description: 'Unix seconds timestamp',
    example: '1647849600',
    insertText: 'time_timestamp',
  },
  {
    label: 'ip',
    kind: 'type',
    description: 'IPv4/IPv6 address',
    example: '192.168.1.100 / ::1',
    insertText: 'ip',
  },
  {
    label: 'ip_net',
    kind: 'type',
    description: 'CIDR network',
    example: '192.168.0.0/24',
    insertText: 'ip_net',
  },
  {
    label: 'port',
    kind: 'type',
    description: 'Port number (1-65535)',
    example: '8080',
    insertText: 'port',
  },
  {
    label: 'kvarr',
    kind: 'type',
    description: 'Key-value pair key=value',
    example: 'key="value"',
    insertText: 'kvarr(${chars@name})',
  },
  {
    label: 'json',
    kind: 'type',
    description: 'JSON object',
    example: '{"strict":true}',
    insertText: 'json(${chars@field})',
  },
  {
    label: 'http/request',
    kind: 'type',
    description: 'HTTP request line',
    example: '"GET /api/users HTTP/1.1"',
    insertText: 'http/request',
  },
  {
    label: 'http/status',
    kind: 'type',
    description: 'HTTP status code',
    example: '200',
    insertText: 'http/status',
  },
  {
    label: 'http/agent',
    kind: 'type',
    description: 'User-Agent',
    example: '"Mozilla/5.0"',
    insertText: 'http/agent',
  },
  {
    label: 'http/method',
    kind: 'type',
    description: 'HTTP method',
    example: '"POST"',
    insertText: 'http/method',
  },
  {
    label: 'hex',
    kind: 'type',
    description: 'Hex string',
    example: '0x1A2B / 1A2B',
    insertText: 'hex',
  },
  {
    label: 'base64',
    kind: 'type',
    description: 'Base64 string',
    example: 'YmFzZTY0ZGF0YQ==',
    insertText: 'base64',
  },
  {
    label: 'sn',
    kind: 'type',
    description: 'Alphanumeric serial number',
    example: 'ABC123XYZ',
    insertText: 'sn',
  },
  {
    label: '_',
    kind: 'type',
    description: 'Ignore this field',
    example: 'Ignore this field',
    insertText: '_',
  },
  {
    label: 'decode/base64',
    kind: 'function',
    description: 'Base64 decode whole line',
    example: 'aGVsbG8=',
    insertText: 'decode/base64',
  },
  {
    label: 'decode/hex',
    kind: 'function',
    description: 'Hex decode whole line',
    example: 'hello',
    insertText: 'decode/hex',
  },
  {
    label: 'unquote/unescape',
    kind: 'function',
    description: 'Remove quotes and unescape',
    example: '"FW\\|action=DROP\\n\\tmsg"',
    insertText: 'unquote/unescape',
  },
  {
    label: 'plg_pipe',
    kind: 'function',
    description: 'Custom preprocessor extension',
    example: '|plg_pipe/dayu|',
    insertText: 'plg_pipe/${name}',
  },
  {
    label: 'take',
    kind: 'function',
    description: 'Select specified field as active',
    example: '|take(name)|',
    insertText: 'take(${name})',
  },
  {
    label: 'last',
    kind: 'function',
    description: 'Select last field as active',
    example: '|last()|',
    insertText: 'last()',
  },
  {
    label: 'f_has',
    kind: 'function',
    description: 'Check field exists',
    example: '|f_has(status)|',
    insertText: 'f_has(${name})',
  },
  {
    label: 'f_chars_has',
    kind: 'function',
    description: 'Check field equals string',
    example: '|f_chars_has(status, success)|',
    insertText: 'f_chars_has(${name}, ${val})',
  },
  {
    label: 'f_chars_not_has',
    kind: 'function',
    description: 'Check field not equal string',
    example: '|f_chars_not_has(level, error)|',
    insertText: 'f_chars_not_has(${name}, ${val})',
  },
  {
    label: 'f_chars_in',
    kind: 'function',
    description: 'Check field in string list',
    example: '|f_chars_in(method, [GET, POST])|',
    insertText: 'f_chars_in(${name}, [...])',
  },
  {
    label: 'f_digit_has',
    kind: 'function',
    description: 'Check field equals number',
    example: '|f_digit_has(code, 200)|',
    insertText: 'f_digit_has(${name}, ${num})',
  },
  {
    label: 'f_digit_in',
    kind: 'function',
    description: 'Check field in number list',
    example: '|f_digit_in(status, [200, 201])|',
    insertText: 'f_digit_in(${name}, [...])',
  },
  {
    label: 'f_ip_in',
    kind: 'function',
    description: 'Check IP in list',
    example: '|f_ip_in(client_ip, [127.0.0.1])|',
    insertText: 'f_ip_in(${name}, [...])',
  },
  {
    label: 'has',
    kind: 'function',
    description: 'Check active field exists',
    example: '|take(name)| has()|',
    insertText: 'has()',
  },
  {
    label: 'chars_has',
    kind: 'function',
    description: 'Check active field equals string',
    example: '|take(status)| chars_has(success)|',
    insertText: 'chars_has(${val})',
  },
  {
    label: 'chars_not_has',
    kind: 'function',
    description: 'Check active field not equal string',
    example: '|take(level)| chars_not_has(error)|',
    insertText: 'chars_not_has(${val})',
  },
  {
    label: 'chars_in',
    kind: 'function',
    description: 'Check active field in string list',
    example: '|take(method)| chars_in([GET, POST])|',
    insertText: 'chars_in([${...}])',
  },
  {
    label: 'digit_has',
    kind: 'function',
    description: 'Check active field equals number',
    example: '|take(code)| digit_has(200)|',
    insertText: 'digit_has(${num})',
  },
  {
    label: 'ip_in',
    kind: 'function',
    description: 'Check active IP in list',
    example: '|take(client_ip)| ip_in([127.0.0.1])|',
    insertText: 'ip_in([${...}])',
  },
  {
    label: 'json_unescape',
    kind: 'function',
    description: 'JSON unescape',
    example: '|take(message)| json_unescape()|',
    insertText: 'json_unescape()',
  },
  {
    label: 'base64_decode',
    kind: 'function',
    description: 'Base64 decode',
    example: '|take(payload)| base64_decode()|',
    insertText: 'base64_decode()',
  },
];

export default WPL_COMPLETION_TABLE;
